services:
  shlips:
    build:
      dockerfile: Dockerfile.dev
    
    environment:
      NODE_ENV: development
    
    volumes:
      - ./:/opt/app
      # Override specific directories with image layer contents
      - node_modules:/opt/app/node_modules
      - svelte-kit:/opt/app/.svelte-kit

volumes:
  node_modules:
  svelte-kit: