services:
  shlips:
    build:
      dockerfile: Dockerfile.dev
    
    environment:
      NODE_ENV: development

    develop:
      watch:
        - action: rebuild
          path:
            - .env
            - package.json
            - svelte.config.js
            - vite.config.js
    
    volumes:
      - ./:/opt/app
      # Override specific directories with image layer contents
      - node_modules:/opt/app/node_modules
      - svelte-kit:/opt/app/.svelte-kit

volumes:
  node_modules:
  svelte-kit: