# docker-compose ingress overrides for traefik
---
version: "3.9"
services:
  shlips:
    labels:
      - traefik.enable=true
      # Traefik will route requests with Host matching the SERVER_NAME environment variable (see .env)
      - traefik.http.routers.shlips-${COMPOSE_PROJECT_NAME}.rule=Host(`${SERVER_NAME}`)

      - traefik.http.routers.shlips-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.shlips-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.shlips-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      - ingress
networks:
  # ingress network
  ingress:
    name: external_web
    external: "true"