services:
  shlips:
    build:
      dockerfile: Dockerfile.dev
    
    environment:
      NODE_ENV: development

    develop:
      watch:
        - action: rebuild
          path: .env
        - action: rebuild
          path: package.json
        - action: rebuild
          path: svelte.config.js
        - action: rebuild
          path: vite.config.js
    
    volumes:
      - ./:/opt/app
      # Override specific directories with image layer contents
      - node_modules:/opt/app/node_modules
      - svelte-kit:/opt/app/.svelte-kit

volumes:
  node_modules:
  svelte-kit: