# docker continuous delivery
# build docker images and push to configured repo, with tags to match branches and git tags
---
name: Build & Deliver
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git commit
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set environment variable for version from git output
        run: echo "VITE_APP_VERSION_STRING=$(git describe --always --tags).$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # =========================
      # Build Production Image
      # =========================
      - name: Build & Push Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && format('ghcr.io/{0}:latest', github.repository) || '' }}
          build-args: |
            VITE_APP_VERSION_STRING=${{ env.VITE_APP_VERSION_STRING }}

      # =========================
      # Build Development Image
      # =========================
      - name: Build & Push Development Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-dev
          build-args: |
            VITE_APP_VERSION_STRING=${{ env.VITE_APP_VERSION_STRING }}
